Data Types Assignment
AustinCodingAcademy/frontend-intermediate-workbook pull request #353
Opened 2018-04-18 14:24 UTC by lesleysab

## Checkpoint Rubric
This is the rubric that your instructor will use to grade your checkpoints. Please do not edit. 

**Checkpoint 1**
- [ ] All tests passed: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript: 30 points

**Checkpoint 2**
- [ ] The application works as it should: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript and the DOM API: 30 points

**Checkpoint 3**
- [ ] Use of React: 25 points
- [ ] Accesses an API: 25 points
- [ ] Proper use of documentation (commenting on code): 25 points
- [ ] The application functions as it should: 25 points

2018-04-18 14:24 UTC, lesleysab commented
Lesley Sablatura Pull Request

2018-04-20 00:01 UTC, stephsingler commented on 01week/datatypes.js
> +  if (num1 <= 5 && num2 >= 10)
This function evaluates if your two arguments are equal to a number that is true. I need the function to evaluate if both arguments are truthy, not equal to something true.

2018-04-20 00:02 UTC, stephsingler commented on 01week/datatypes.js
> +  if (num1 <= 5 || num2 >= 10)
This function evaluates if one of your arguments is equal to something true. I need the function to evaluate if one argument is truthy.

2018-04-20 00:03 UTC, stephsingler commented on 01week/datatypes.js
> +    return ('false');
This function evaluates if your two arguments are equal to a false number. I need the function to evaluate if both arguments are falsey, not equal to a false value.

2018-04-20 00:03 UTC, stephsingler requested changes
Great start just look at the last 3 comments and make sure your function are evaluating...not checking true/false values

2018-04-20 04:55 UTC, closed without merging